version: '3.8'

services:
  pixyship-frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - './frontend/:/app'
      - '/app/node_modules'
    command: /bin/sh -c "npm run serve"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development

  pixyship-backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - './backend/:/app'
    environment:
      - FLASK_ENV=development
    depends_on:
      - pixyship-database

  pixyship-database:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=pixyship
      - POSTGRES_PASSWORD=pixyship
      - POSTGRES_DB=pixyship
      - PGDATA=/var/lib/postgresql/data/
    volumes:
      - ./pgdata:/var/lib/postgresql/data
