version: '3.8'

services:
  pixyship-frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
      target: development-stage
    ports:
      - '8080:8080'
    volumes:
      - './frontend/:/app'
      - '/app/node_modules'

  pixyship-backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
      target: development-stage
    ports:
      - '5000:5000'
    volumes:
      - './backend/:/app'
    depends_on:
      - pixyship-database

  pixyship-database:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=pixyship
      - POSTGRES_PASSWORD=pixyship
      - POSTGRES_DB=pixyship
      - PGDATA=/var/lib/postgresql/data/
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  pixyship-migration:
    build:
      context: ./backend/
      dockerfile: Dockerfile
      target: development-stage
    command: alembic upgrade head
    depends_on:
      - pixyship-database
