services:
  backend:
    build: .
    ports:
      - "${BACKEND_PORT:-5000}:5000"
    environment:
      - FLASK_SQLALCHEMY_DATABASE_URI=postgresql+psycopg://pixyship:pixyship@db:5432/pixyship
    command: flask run --host=0.0.0.0 --port=5000 --debug
    stop_signal: SIGINT
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=pixyship
      - POSTGRES_PASSWORD=pixyship
      - POSTGRES_DB=pixyship
      - PGDATA=/var/lib/postgresql/data/
    volumes:
      - ./pgdata:/var/lib/postgresql/data
