[project]
name = "pixyship"
version = "2.8.0"
description = "PixyShip is a reference site for the game Pixel Starships."
authors = [
    { name = "solevis", email = "solevis@protonmail.com" }
]
dependencies = [
    "Flask==2.3.2",
    "Flask-Cors==4.0.0",
    "Flask-SQLAlchemy==3.0.5",
    "psycopg2-binary==2.9.6",
    "requests==2.31.0",
    "schedule==1.2.0",
    "contexttimer==0.3.3",
    "alembic==1.11.1",
]
readme = "README.md"
requires-python = ">= 3.11"

[tool.rye]
managed = true
virtual = true
dev-dependencies = [
    "pytest==7.4.0",
]

[tool.ruff]
target-version = "py311"
line-length = 120
indent-width = 4

[tool.pytest.ini_options]
pythonpath = "."
addopts = [
    "--import-mode=importlib",
]
