name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the backend Docker image
      working-directory: ./backend
      run: docker build . --file Dockerfile --tag ${{ github.repository }}-backend:$(date +%s)
    - name: Build the frontend Docker image
      working-directory: ./frontend
      run: docker build . --file Dockerfile --tag ${{ github.repository }}-frontend:$(date +%s)
