name: Node.js 15.x

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install requirements
      working-directory: ./frontend
      run: npm ci
    - name: Build UI
      working-directory: ./frontend
      run: npm run build --if-present
